name: "AccuKnox DAST Scan"
description: "Run AccuKnox Dynamic Application Security Testing (DAST) scan on a web application"

branding:
  icon: "shield"
  color: "purple"

inputs:
  accuknox_token:
    description: "API token for AccuKnox CSPM Control Plane"
    required: true
  accuknox_label:
    description: "Label for scan results in AccuKnox Console"
    required: true
  accuknox_endpoint:
    description: "CSPM Control Plane Domain"
    required: true
  target_url:
    description: "The URL of the web application to scan"
    required: true
  dast_scan_type:
    description: "DAST scan type (baseline or full-scan)"
    required: false
    default: "baseline"
  severity_threshold:
    description: "Minimum severity to fail the scan (LOW, MEDIUM, HIGH)"
    required: false
    default: "HIGH"
  soft_fail:
    description: "Do not return an error code if vulnerabilities are found"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install AccuKnox ASPM Scanner
      shell: bash
      run: |
        echo "Installing AccuKnox ASPM scanner..."
        pip install https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox_aspm_scanner-0.13.4-py3-none-any.whl --break-system-packages
        echo "AccuKnox ASPM scanner installed successfully."

    - name: Prepare scan directory
      shell: bash
      run: |
        mkdir -p /tmp/scan-dir
        chmod 777 /tmp/scan-dir
        echo "Scan directory ready at /tmp/scan-dir"

    - name: Run AccuKnox DAST Scan
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        TARGET_URL: ${{ inputs.target_url }}
        DAST_SCAN_TYPE: ${{ inputs.dast_scan_type }}
        SEVERITY_THRESHOLD: ${{ inputs.severity_threshold }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
      run: |
        set -e
        cd /tmp/scan-dir

        echo "Starting AccuKnox DAST scan..."

        if [ "$DAST_SCAN_TYPE" = "full-scan" ]; then
          DAST_SCAN_SCRIPT="zap-full-scan.py"
        else
          DAST_SCAN_SCRIPT="zap-baseline.py"
        fi

        SOFT_FAIL_ARG=""
        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        CMD="$DAST_SCAN_SCRIPT -t $TARGET_URL -I"

        echo accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --severity-threshold "$SEVERITY_THRESHOLD" --command "$CMD" --container-mode
        accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --severity-threshold "$SEVERITY_THRESHOLD" --command "$CMD" --container-mode

        cd -
